[project]
name = "capstonedev"
version = "0.1.0"
description = "Website to facilitate interations with labs for online students."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "gunicorn>=24.1.1",
]
